const usersData = [
    { name: "Иван", surname: "Иванов", city: "Москва" },
    { name: "Елена", surname: "Петрова", city: "Санкт-Петербург" },
    { name: "Алексей", surname: "Смирнов", city: "Новосибирск" },
    { name: "Ольга", surname: "Сергеева", city: "Екатеринбург" },
    { name: "Сергей", surname: "Кузнецов", city: "Красноярск" },
    { name: "Наталья", surname: "Павлова", city: "Владивосток" },
    { name: "Дмитрий", surname: "Козлов", city: "Казань" },
    { name: "Анна", surname: "Морозова", city: "Челябинск" },
    { name: "Александр", surname: "Васильев", city: "Омск" },
    { name: "Мария", surname: "Петрова", city: "Самара" },
    { name: "Игорь", surname: "Соколов", city: "Ростов-на-Дону" },
    { name: "Екатерина", surname: "Михайлова", city: "Уфа" },
    { name: "Артем", surname: "Федоров", city: "Краснодар" },
    { name: "Татьяна", surname: "Новикова", city: "Пермь" },
    { name: "Владимир", surname: "Максимов", city: "Воронеж" },
    { name: "Алиса", surname: "Александрова", city: "Волгоград" },
    { name: "Павел", surname: "Семенов", city: "Курск" },
    { name: "Евгения", surname: "Николаева", city: "Тюмень" },
    { name: "Никита", surname: "Игнатьев", city: "Иркутск" },
    { name: "Маргарита", surname: "Куликова", city: "Томск" },
    { name: "Артур", surname: "Дмитриев", city: "Астрахань" },
    { name: "Юлия", surname: "Комарова", city: "Хабаровск" },
    { name: "Денис", surname: "Григорьев", city: "Барнаул" },
    { name: "Елизавета", surname: "Тимофеева", city: "Ярославль" },
    { name: "Максим", surname: "Фролов", city: "Ульяновск" },
    { name: "Ангелина", surname: "Савельева", city: "Ижевск" },
    { name: "Илья", surname: "Лебедев", city: "Тула" },
    { name: "Алина", surname: "Захарова", city: "Кемерово" },
    { name: "Роман", surname: "Герасимов", city: "Рязань" },
    { name: "Евгений", surname: "Сидоров", city: "Набережные Челны" },
    { name: "Валерия", surname: "Полякова", city: "Магнитогорск" },
    { name: "Станислав", surname: "Киселев", city: "Тверь" },
    { name: "Оксана", surname: "Белова", city: "Балашиха" },
    { name: "Игнат", surname: "Богданов", city: "Сочи" },
    { name: "Юлиана", surname: "Андреева", city: "Ставрополь" },
    { name: "Василий", surname: "Кузьмин", city: "Улан-Удэ" },
    { name: "Евдокия", surname: "Мартынова", city: "Иркутск" },
    { name: "Святослав", surname: "Логинов", city: "Йошкар-Ола" },
    { name: "Милана", surname: "Сергеева", city: "Тамбов" },
    { name: "Арсений", surname: "Афанасьев", city: "Бийск" },
    { name: "Ева", surname: "Головина", city: "Курган" },
    { name: "Глеб", surname: "Королев", city: "Калуга" },
    { name: "Лидия", surname: "Миронова", city: "Волжский" },
    { name: "Артемий", surname: "Степанов", city: "Сургут" },
    { name: "Эльвира", surname: "Фомина", city: "Владикавказ" },
    { name: "Артем", surname: "Панов", city: "Смоленск" },
    { name: "Людмила", surname: "Гусева", city: "Саранск" },
    { name: "Валентин", surname: "Котов", city: "Грозный" },
    { name: "Алиса", surname: "Широкова", city: "Вологда" },
    { name: "Илья", surname: "Осипов", city: "Якутск" },
    { name: "Ника", surname: "Макарова", city: "Оренбург" },
    { name: "Степан", surname: "Белов", city: "Пенза" },
];

module.exports = usersData;